# Generated by Django 4.2.29 on 2026-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary')], max_length=1)),
                ('experience_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Experienced')], max_length=1)),
                ('pace', models.CharField(choices=[('S', 'Slow'), ('A', 'Average'), ('F', 'Fast')], max_length=1)),
            ],
        ),
    ]
